server:
  port: 8081

spring:
  mail:
    # 发送邮件的服务器
    host: xxxx
    fromName: \u4xxx\u4xxx\u4xxx
    # 发送邮件的邮箱地址
    username: xxx@email.com
    # 发送邮件的邮箱密码
    password: password
    # 接收邮件的邮箱
    to: xxx@email.com
    # 默认编码格式
    default-encoding: UTF-8
    # 发送邮件的地址，和上面username一致
    from: xxx@email.com