server:
  port: 8081

spring:
  mail:
    # 发送邮件的服务器
    host: you.xiang.com
    fromName: 我是名字
    # 发送邮件的邮箱地址
    username: youxiang@yx.com
    # 发送邮件的邮箱密码
    password: kmsys_202005
    # 接收邮件的邮箱
    to: shoujianren@qq.com
    # 默认编码格式
    default-encoding: UTF-8
    # 发送邮件的地址，和上面username一致
    from: youxiang@yx.com