server:
  port: 8081

# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frank-dao-user?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# mybaties-plus
mybatis-plus:
  mapper-locations: classpath:com/frank/mybatisplus/mapper/xml/*.xml
  type-aliases-package: com.frank.mybatisplus.entity
  configuration:
    map-underscore-to-camel-case: true

