server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sub_database_table0
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # 配置ShardingSphere
  shardingsphere:
    # 配置ShardingSphere
    datasource:
      names: sub_database_table0,sub_database_table1
      sub_database_table0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sub_database_table0
        username: root
        password: root
      sub_database_table1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sub_database_table1
        username: root
        password: root
    rules:
      sharding:
        tables:
          order_main:
            # 配置 order_main 表规则
            actual-data-nodes: sub_database_table$->{0..1}.t_order$->{0..1}
            # 配置分库策略
            database-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: database_inline
            # 配置分表策略
            table-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: table_inline
        # 配置 分片算法
        sharding-algorithms:
          database_inline:
            type: INLINE
            props:
              algorithm-expression: sub_database_table$->{user_id % 2}
          table_inline:
            type: INLINE
            props:
              algorithm-expression: sub_database_table$->{order_id % 2}
