spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootjpa?serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update    #更新或者创建表
    show-sql: true        #控制台显示sql