server:
  port: 8081
spring:
  application:
    name: Spring-Boot-Junit
  # 配置freemarker支持
  mvc:
    view:
      # 默认前缀
      prefix: /
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    thymeleaf:
      prefix: classpath:/templates
      cache: true
    servlet:
      multipart:
        max-file-size: -1
        max-request-size: -1