# redis
spring:
  redis:
    enable: true
    # Connection URL, will override host, port and password (user will be ignored), e.g. redis://user:password@example.com:6379
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 5000
    database: 7
    redisson:
      file: classpath:redisson.yml
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 800 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 2 # 连接池中的最小空闲连接
server:
  port: 8081
