# 这里自己配要发送的邮件地址信息
spring:
  mail:
    # 发送邮件的服务器
    host: xxx
    fromName: 我是发送人名字
    # 发送邮件的邮箱地址
    username: xxxx@xxx.com
    # 发送邮件的邮箱密码
    password: xxxxxx
    # 接收邮件的邮箱
    to: xxxxx
    # 默认编码格式
    default-encoding: UTF-8
    # 发送邮件的地址，和上面username一致
    from: xxxxx